name: 01 - Building Blocks 

on: push

jobs:
    echo-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say Hello
              run: echo "Hello, World"
    echo-goodbye:
        runs-on: ubuntu-latest
        steps:
            - name: Say goodBye
              run: echo "goodbye!"
    echo-Welcome:
        runs-on: ubuntu-latest
        steps:
            - name: Say Welcome
              run: echo "Welcome All"
            - name: Success step
              run: |
                 echo "I will Succeed"
                 exit 0